account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import TemplateView

from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm
from .views import (EducationDelete, InstitutionList, UpdateEducation,
                    account_activate, account_register, apply_author, author_application_accept, author_application_delete, author_application_detail, author_application_list, edit_profile,
                    follow_toggle, user_profile)

app_name = "account"

urlpatterns = [
    path("register/", account_register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html",
         form_class=UserLoginForm), name="login",),
    path("activate/<slug:uidb64>/<slug:token>)/",
         account_activate, name="activate"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("password_reset/", auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
         success_url="password_reset_email_confirm", email_template_name="account/password_reset/password_reset_email.html", form_class=PwdResetForm,), name="pwdreset",),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset/password_reset_confirm.html",
         success_url="password_reset_complete/", form_class=PwdResetConfirmForm,), name="password_reset_confirm",),
    path("password_reset/password_reset_email_confirm/", TemplateView.as_view(
        template_name="account/password_reset/reset_status.html"), name="password_reset_done",),
    path("password_reset_confirm/Mg/password_reset_complete/", TemplateView.as_view(
        template_name="account/password_reset/reset_status.html"), name="password_reset_complete",),

    # dashboard
    path('profile/edit/', edit_profile, name="edit_profile"),
    path('profile/<slug:slug>/', user_profile, name="user_profile"),
    
    #follow
    path('follow/', follow_toggle, name="follow_toggle"),
    path('ins/', InstitutionList.as_view(), name="institution_list"),
    path('ins-edit/<int:pk>/', UpdateEducation.as_view(), name="institution_update"),
    path('ins-delete/<int:pk>/', EducationDelete.as_view(), name="institution_delete"),


    path("author-application-list/", author_application_list, name="author_application_list"),
    path("author-application/", apply_author, name="apply_author"),
    path("author-application-accept/<int:pk>/", author_application_accept, name="author_application_accept"),
    path("author-application-delete/<int:pk>/", author_application_delete, name="author_application_delete"),
    path("author-application-detail/<int:pk>/", author_application_detail, name="author_application_detail"),
]

keep/urls.py
from django.urls import path

from .views import KeepCreate, KeepDelete, KeepDetail, KeepList, KeepUpdate

app_name = "keep"

urlpatterns = [
    path('my-keep-list', KeepList.as_view(), name="keep_list"),
    path('create/', KeepCreate.as_view(), name="keep_create"),
    path('detail/<int:pk>/', KeepDetail.as_view(), name="keep_detail"),
    path('update/<int:pk>/', KeepUpdate.as_view(), name="keep_update"),
    path('delete/<int:pk>/', KeepDelete.as_view(), name="keep_delete"),
]

notification/urls.py
from django.urls import path

from .views import DeleteNotification, ShowNOtifications

app_name = "notification"
urlpatterns = [
   	path('', ShowNOtifications, name='show-notifications'),
   	path('<noti_id>/delete', DeleteNotification, name='delete-notification'),
]

post/urls.py
from django.urls import path

from .views import (BlogDelete, CreatePost, MyPosts, PostList, UpdatePost,
                    bookmark, bookmark_list, category_based_list,
                    category_list, deactivate_blog, post_details,
                    subscribe_category, tag_based_list, writters_posts)

app_name = "post"

urlpatterns = [
    path('', PostList, name='post_list'),
    path('details/<slug:slug>', post_details, name='post_details'),
    path('write/', CreatePost.as_view(), name='create_post'),
    path('edit/<pk>/', UpdatePost.as_view(), name='edit_blog'),
    path('my-blogs/', MyPosts, name='my_blogs'),
    path('deactivate-blog/<pk>/', deactivate_blog, name="deactivate_blog"),
    path('blog-delete/<int:pk>/', BlogDelete.as_view(), name="blog_delete"),

    path('add-bookmark/', bookmark, name="bookmark"),
    path('bookmark-list/', bookmark_list, name="bookmark_list"),


    path('category/<slug:category_slug>/',
         category_based_list, name='category_based_list'),
    path('tag/<slug:slug>/', tag_based_list, name="tag_based_list"),

    path("writter-posts/<slug:slug>/", writters_posts, name="writters_posts"),
    path('subscribe-category/', subscribe_category, name="subscribe_category"),
    path('category-list/', category_list, name="category_list"),
]

scientific_application/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
    path('like/', include('like.urls', namespace="like")),
    path('comment/', include('comment.urls', namespace="comment")),
    path('keep/', include('keep.urls', namespace="keep")),
    path('notification/', include('notification.urls', namespace="notification")),
    path("", include("post.urls", namespace="post")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/models.py
from django.contrib.auth import get_user_model
from django.db import models

from comment.models import Comment
from post.models import Post

# Create your models here.
User = get_user_model()


class Notification(models.Model):
    NOTIFICATION_TYPES = ((1, 'Like'), (2, 'Comment'), (3, 'Follow'),
                          (4, 'Welcome Message'), (5, 'Author Application Accepted'), (6, 'Author Application Denied'))

    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="noti_post", blank=True, null=True)
    comment = models.ForeignKey(
        Comment, on_delete=models.DO_NOTHING, related_name="noti_post", blank=True, null=True)
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="noti_from_user", blank=True, null=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="noti_to_user", blank=True, null=True)
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
    text_preview = models.CharField(max_length=90, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.sender}===>{self.user}==>{self.notification_type}"

notification/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .models import Notification


# Create your views here.
@login_required
def ShowNOtifications(request):
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date')
    # seen_notifications = Notification.objects.filter(user=user,is_seen=True).order_by('-date')
    Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)
    # Notification.objects.filter(user=user, is_seen=True).update(is_seen=False)
    context = {
        'notifications': notifications,
        # "seen_notifications": seen_notifications,
        }
    return render(request, 'notification/notification.html', context)

@login_required
def DeleteNotification(request, noti_id):
    user = request.user
    notification = get_object_or_404(Notification, id=noti_id)
    if notification.user == user:
        Notification.objects.filter(id=noti_id, user=user).delete()
    return redirect('notification:show-notifications')


def CountNotifications(request):
    count_notifications = 0
    if request.user.is_authenticated:
        count_notifications = Notification.objects.filter(user=request.user, is_seen=False).count()
        
    context = {
        'count_notifications':count_notifications
        }
    return context

templates/notification/notification.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Notifications{% endblock title %}
{% block content %}
    <div class="container">
        <h3 class="my-2">Notification</h3>
        <div class="dropdown-divider"></div>


        {% for notification in notifications %}
            <div class="card my-2 bg-light">
                <div class="card-body">
                    <p>

                        {% if notification.notification_type == 1 %}
                            <img src="{{ notification.sender.image.url }}" alt="{{ notification.sender.name }}" width="50" height="50">
                            <a href="{% url 'account:user_profile' slug=notification.sender.account_slug %}" class="text-decoration-none text-black fw-bolder">{{ notification.sender.name }}</a>
                            Liked Your Post <a href="{% url 'post:post_details' slug=notification.post.slug %}" class="text-decoration-none text-black fw-bold">{{ notification.post.post_title }}</a>

                        
                        {% elif notification.notification_type == 2 %}
                            <img src="{{ notification.sender.image.url }}" alt="{{ notification.sender.name }}" width="50" height="50">
                            <a href="{% url 'account:user_profile' slug=notification.sender.account_slug %}" class="text-decoration-none text-black fw-bolder">{{ notification.sender.name }}</a>
                            Commented To Your Post <a href="{% url 'post:post_details' slug=notification.post.slug %}" class="text-decoration-none text-black fw-bold">{{ notification.post.post_title }}</a>
                        
                        {% elif notification.notification_type == 3 %}
                            <img src="{{ notification.sender.image.url }}" alt="{{ notification.sender.name }}" width="50" height="50">
                            <a href="{% url 'account:user_profile' slug=notification.sender.account_slug %}" class="text-decoration-none text-black fw-bolder">{{ notification.sender.name }}</a>
                            Followed You!
                        
                        {% elif notification.notification_type == 4 %}
                            <div class="fw-bolder">Welcome {{ notification.user.name }} to Our Scientific Article Application!</div>
                        
                        {% elif notification.notification_type == 5 %}
                            Congrtulation! Your Application to be an author has been accepted!
                        {% elif notification.notification_type == 6 %}
                            Sorry! Your Application to be an author has been Denied!
                        {% endif %}

                        &nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url 'notification:delete-notification' notification.id %}"><i class="bi bi-eraser-fill text-danger"></i></a>

                    </p>
                    <p>{{ notification.date|naturaltime }}</p>
                </div>
            </div>
        {% endfor %}




    </div>

{% endblock content %}