keep/urls.py
from django.urls import path

from .views import KeepCreate, KeepDelete, KeepDetail, KeepList, KeepUpdate

app_name = "keep"

urlpatterns = [
    path('my-keep-list', KeepList.as_view(), name="keep_list"),
    path('create/', KeepCreate.as_view(), name="keep_create"),
    path('detail/<int:pk>/', KeepDetail.as_view(), name="keep_detail"),
    path('update/<int:pk>/', KeepUpdate.as_view(), name="keep_update"),
    path('delete/<int:pk>/', KeepDelete.as_view(), name="keep_delete"),
]

scientific_application/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
    path('like/', include('like.urls', namespace="like")),
    path('comment/', include('comment.urls', namespace="comment")),
    path('keep/', include('keep.urls', namespace="keep")),
    path('notification/', include('notification.urls', namespace="notification")),
    path("", include("post.urls", namespace="post")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

keep/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
User = get_user_model()


class Keep(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    title = models.CharField(
        max_length=70, help_text="Max Length 80 Character")
    detail = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.author}===>{self.title}"

keep/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .models import Keep
from .permissions import LoginRequiredandAuthorMixin


# Create your views here.
class KeepList(LoginRequiredMixin, ListView):
    model = Keep

    def get_queryset(self):
        return Keep.objects.filter(author=self.request.user).order_by("-id")
    context_object_name = "keeps"
    ordering = "-id"
    paginate_by = 12
    template_name = "keep/keeplist.html"


class KeepCreate(LoginRequiredMixin, CreateView):
    model = Keep
    template_name = "keep/keepcreate.html"
    success_url = "keep:keep_list"
    fields = ('title', 'detail',)

    def form_valid(self, form):
        post_object = form.save(commit=False)
        post_object.author = self.request.user
        post_object.save()
        return HttpResponseRedirect(reverse('keep:keep_list'))


class KeepDetail(LoginRequiredandAuthorMixin, DetailView):
    model = Keep
    template_name = "keep/keepdetail.html"
    context_object_name = "keep"


class KeepUpdate(LoginRequiredandAuthorMixin, UpdateView):
    model = Keep
    template_name = "keep/keepupdate.html"
    fields = ('title', 'detail',)
    context_object_name = "keep"

    def get_success_url(self, **kwargs):
        return reverse('keep:keep_detail', kwargs={'pk': self.object.pk})


class KeepDelete(LoginRequiredandAuthorMixin, DeleteView):
    model = Keep
    template_name = "keep/keep_confirm_delete.html"
    context_object_name = "keep"

    def get_success_url(self, **kwargs):
        return reverse("keep:keep_list")

templates/keep/keep_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Are You Sure?{% endblock title %}
{% block content %}
    <div class="container my-2">
        <form method="post">
            {% csrf_token %}
            <center><p>Are you sure you want to delete "{{ keep.title }}"?</p></center>
            <div class="d-grid gap-2 col-6 mx-auto my-3">
                <button type="submit" class="btn btn-danger btn-sm">Delete the Note</button>
            </div>
        </form>
        <div class="flex-column justify-content-center mx-auto pb-3">
            <div class="text-center mt-3">
                <a href="{% url "keep:keep_detail" keep.pk %}" class="btn btn-outline-secondary btn-sm">
                    Back to Note
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/keep/keepcreate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create Keep{% endblock title %}
{% block content %}
    <div class="container">
        <h2 class="text-center mt-3">Add a Note</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid gap-2 col-6 mx-auto my-3">
                <button type="submit" class="btn btn-success">Create</button>
            </div>
        </form>
        <div class="flex-column justify-content-center mx-auto pb-3">
            <div class="text-center mt-3">
                <a href="{% url 'keep:keep_list' %}" class="btn btn-outline-secondary btn-sm mt-1">Go back to Home</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/keep/keepdetail.html
{% extends 'base.html' %}
{% block title %} {{ keep.title }}{% endblock title %}
{% block content %}
    <div class="container my-3 font-monospace">
        <h2 class="display-6 ">{{ keep.title }}</h2>
        <p class="fst-italic">{{ keep.created }}</p>
        <span class="d-flex">
            <a href="{% url 'keep:keep_update' keep.pk %}" class="btn btn-warning btn-sm">Edit</a> &nbsp;
            <a href="{% url 'keep:keep_delete' keep.pk %}" class="btn btn-danger btn-sm">Delete</a>
        </span>
        <p class="">
            {{ keep.detail|linebreaks }}
        </p>
    </div>
{% endblock content %}

templates/keep/keeplist.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Keep | Home{% endblock title %}
{% block content %}
    <div class="container font-monospace">
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Keep Your Notes Here</h1>
                    <p class="lead text-muted">
                        Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.
                    </p>
                    <p>
                        <a href="{% url 'keep:keep_create' %}" class="btn btn-primary my-2">Create a Keep</a>
                        <a href="" class="btn btn-secondary my-2">Secondary action</a>
                    </p>
                </div>
            </div>
        </section>
        <hr class="dropdown-divider">
        
        {% if keeps %}
            <div class="row align-items-md-stretch my-4">
                {% for keep in keeps %}
                    <div class="col-md-6 mt-3">
                        <div class="h-80 p-3 bg-light border rounded-3">
                            <h3>{{ keep.title }}</h3>
                            <p>{{ keep.created|naturaltime }}</p>
                            <p>
                                {{ keep.detail|slice:100 }}
                            </p>

                            <span class="d-flex">
                                <a href="{% url 'keep:keep_detail' keep.pk %}" class="btn btn-outline-secondary btn-sm">Read the Note</a> &nbsp;
                                <a href="{% url 'keep:keep_update' keep.pk %}" class="btn btn-outline-warning btn-sm">Edit</a> &nbsp;
                                <a href="{% url 'keep:keep_delete' keep.pk %}" class="btn btn-outline-danger btn-sm">Delete</a>
                            </span>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!-- Pagination-->
            
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="">Previous</a>
                        </li>
                    {% endif %}
                    <span class="current">
                        <a class="page-link">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </a>
                    </span>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% else %}
            <h2 class="display-6 text-center my-4">
                Currently you have no Notes
            </h2>
        {% endif %}

    </div>
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
        </div>
    </footer>
{% endblock content %}

templates/keep/keepupdate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} {{ keep.title }}{% endblock title %}
{% block content %}
    <div class="container">
        <h2 class="text-center mt-3">Edit your Note</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid gap-2 col-6 mx-auto my-3">
                <button type="submit" class="btn btn-success">Create</button>
            </div>
        </form>
        <div class="flex-column justify-content-center mx-auto pb-3">
            <div class="text-center mt-3">
                <a href="{% url "keep:keep_detail" keep.pk %}" class="btn btn-outline-secondary btn-sm mt-1">
                    Go back to Home
                </a>
            </div>
        </div>
    </div>
{% endblock content %}