account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import TemplateView

from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm
from .views import (EducationDelete, InstitutionList, UpdateEducation,
                    account_activate, account_register, apply_author, author_application_accept, author_application_delete, author_application_detail, author_application_list, edit_profile,
                    follow_toggle, user_profile)

app_name = "account"

urlpatterns = [
    path("register/", account_register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html",
         form_class=UserLoginForm), name="login",),
    path("activate/<slug:uidb64>/<slug:token>)/",
         account_activate, name="activate"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("password_reset/", auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
         success_url="password_reset_email_confirm", email_template_name="account/password_reset/password_reset_email.html", form_class=PwdResetForm,), name="pwdreset",),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset/password_reset_confirm.html",
         success_url="password_reset_complete/", form_class=PwdResetConfirmForm,), name="password_reset_confirm",),
    path("password_reset/password_reset_email_confirm/", TemplateView.as_view(
        template_name="account/password_reset/reset_status.html"), name="password_reset_done",),
    path("password_reset_confirm/Mg/password_reset_complete/", TemplateView.as_view(
        template_name="account/password_reset/reset_status.html"), name="password_reset_complete",),

    # dashboard
    path('profile/edit/', edit_profile, name="edit_profile"),
    path('profile/<slug:slug>/', user_profile, name="user_profile"),
    
    #follow
    path('follow/', follow_toggle, name="follow_toggle"),
    path('ins/', InstitutionList.as_view(), name="institution_list"),
    path('ins-edit/<int:pk>/', UpdateEducation.as_view(), name="institution_update"),
    path('ins-delete/<int:pk>/', EducationDelete.as_view(), name="institution_delete"),


    path("author-application-list/", author_application_list, name="author_application_list"),
    path("author-application/", apply_author, name="apply_author"),
    path("author-application-accept/<int:pk>/", author_application_accept, name="author_application_accept"),
    path("author-application-delete/<int:pk>/", author_application_delete, name="author_application_delete"),
    path("author-application-detail/<int:pk>/", author_application_detail, name="author_application_detail"),
]

keep/urls.py
from django.urls import path

from .views import KeepCreate, KeepDelete, KeepDetail, KeepList, KeepUpdate

app_name = "keep"

urlpatterns = [
    path('my-keep-list', KeepList.as_view(), name="keep_list"),
    path('create/', KeepCreate.as_view(), name="keep_create"),
    path('detail/<int:pk>/', KeepDetail.as_view(), name="keep_detail"),
    path('update/<int:pk>/', KeepUpdate.as_view(), name="keep_update"),
    path('delete/<int:pk>/', KeepDelete.as_view(), name="keep_delete"),
]

notification/urls.py
from django.urls import path

from .views import DeleteNotification, ShowNOtifications

app_name = "notification"
urlpatterns = [
   	path('', ShowNOtifications, name='show-notifications'),
   	path('<noti_id>/delete', DeleteNotification, name='delete-notification'),
]

post/urls.py
from django.urls import path

from .views import (BlogDelete, CreatePost, MyPosts, PostList, UpdatePost,
                    bookmark, bookmark_list, category_based_list,
                    category_list, deactivate_blog, post_details,
                    subscribe_category, tag_based_list, writters_posts)

app_name = "post"

urlpatterns = [
    path('', PostList, name='post_list'),
    path('details/<slug:slug>', post_details, name='post_details'),
    path('write/', CreatePost.as_view(), name='create_post'),
    path('edit/<pk>/', UpdatePost.as_view(), name='edit_blog'),
    path('my-blogs/', MyPosts, name='my_blogs'),
    path('deactivate-blog/<pk>/', deactivate_blog, name="deactivate_blog"),
    path('blog-delete/<int:pk>/', BlogDelete.as_view(), name="blog_delete"),

    path('add-bookmark/', bookmark, name="bookmark"),
    path('bookmark-list/', bookmark_list, name="bookmark_list"),


    path('category/<slug:category_slug>/',
         category_based_list, name='category_based_list'),
    path('tag/<slug:slug>/', tag_based_list, name="tag_based_list"),

    path("writter-posts/<slug:slug>/", writters_posts, name="writters_posts"),
    path('subscribe-category/', subscribe_category, name="subscribe_category"),
    path('category-list/', category_list, name="category_list"),
]

scientific_application/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
    path('like/', include('like.urls', namespace="like")),
    path('comment/', include('comment.urls', namespace="comment")),
    path('keep/', include('keep.urls', namespace="keep")),
    path('notification/', include('notification.urls', namespace="notification")),
    path("", include("post.urls", namespace="post")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block favicon %}
        <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}" />
    {% endblock favicon %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    {% block style %}{% endblock style %}
    <title>{% block title %}Scientific Blog{% endblock title %} {% if count_notifications > 0 %} ({{ count_notifications }}) {% endif %} </title>
</head>

<body>
    <div class="">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'post:post_list' %}">
                    <img src="{% static 'logo/logo.png' %}" alt="" height="50" width="70">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-secondary btn-sm  mx-2 my-1" aria-current="page" href="">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-secondary btn-sm  mx-2 my-1" href="">Link</a>
                        </li>
                        {% if request.user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link btn btn-outline-secondary btn-sm  mx-2 my-1" href="{% url 'account:author_application_list' %}">Applications</a>
                            </li>
                        {% endif %}
                        
                        {% if request.user.is_authenticated %}
                            <a class="btn btn-outline-info btn-sm  mx-2 my-1" aria-current="page" href="{% url 'account:user_profile' user.account_slug %}">Account</a>
                            <a class="btn btn-outline-secondary btn-sm mx-2 my-1" aria-current="page" href="{% url 'notification:show-notifications' %}">
                                {% if count_notifications > 0 %}
                                    Notifications <span class="badge bg-secondary">{{ count_notifications }}</span>
                                {% else %}
                                    Notification
                                {% endif %}
                            </a>
                            
                            {% comment %} <a class="btn btn-outline-warning btn-sm font-monospace mx-2 my-1" aria-current="page" href="">Logout</a> {% endcomment %}
                        {% else %}
                            <a class="btn btn-outline-info btn-sm font-monospace mx-2 my-1" aria-current="page" href="{% url 'account:login' %}">Login</a>
                            <a class="btn btn-outline-primary btn-sm font-monospace mx-2 my-1" aria-current="page" href="{% url 'account:register' %}">Registration</a>
                        {% endif %}
                        
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    
                </div>
                
            </div>
        </nav>
        {% block content %}{% endblock content %}
        
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block script %}{% endblock script %}
</body>

</html>