account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import TemplateView

from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm
from .views import (EducationDelete, InstitutionList, UpdateEducation,
                    account_activate, account_register, apply_author, author_application_accept, author_application_delete, author_application_detail, author_application_list, edit_profile,
                    follow_toggle, user_profile)

app_name = "account"

urlpatterns = [
    path("register/", account_register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html",
         form_class=UserLoginForm), name="login",),
    path("activate/<slug:uidb64>/<slug:token>)/",
         account_activate, name="activate"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("password_reset/", auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
         success_url="password_reset_email_confirm", email_template_name="account/password_reset/password_reset_email.html", form_class=PwdResetForm,), name="pwdreset",),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset/password_reset_confirm.html",
         success_url="password_reset_complete/", form_class=PwdResetConfirmForm,), name="password_reset_confirm",),
    path("password_reset/password_reset_email_confirm/", TemplateView.as_view(
        template_name="account/password_reset/reset_status.html"), name="password_reset_done",),
    path("password_reset_confirm/Mg/password_reset_complete/", TemplateView.as_view(
        template_name="account/password_reset/reset_status.html"), name="password_reset_complete",),

    # dashboard
    path('profile/edit/', edit_profile, name="edit_profile"),
    path('profile/<slug:slug>/', user_profile, name="user_profile"),
    
    #follow
    path('follow/', follow_toggle, name="follow_toggle"),
    path('ins/', InstitutionList.as_view(), name="institution_list"),
    path('ins-edit/<int:pk>/', UpdateEducation.as_view(), name="institution_update"),
    path('ins-delete/<int:pk>/', EducationDelete.as_view(), name="institution_delete"),


    path("author-application-list/", author_application_list, name="author_application_list"),
    path("author-application/", apply_author, name="apply_author"),
    path("author-application-accept/<int:pk>/", author_application_accept, name="author_application_accept"),
    path("author-application-delete/<int:pk>/", author_application_delete, name="author_application_delete"),
    path("author-application-detail/<int:pk>/", author_application_detail, name="author_application_detail"),
]

keep/urls.py
from django.urls import path

from .views import KeepCreate, KeepDelete, KeepDetail, KeepList, KeepUpdate

app_name = "keep"

urlpatterns = [
    path('my-keep-list', KeepList.as_view(), name="keep_list"),
    path('create/', KeepCreate.as_view(), name="keep_create"),
    path('detail/<int:pk>/', KeepDetail.as_view(), name="keep_detail"),
    path('update/<int:pk>/', KeepUpdate.as_view(), name="keep_update"),
    path('delete/<int:pk>/', KeepDelete.as_view(), name="keep_delete"),
]

post/urls.py
from django.urls import path

from .views import (BlogDelete, CreatePost, MyPosts, PostList, UpdatePost,
                    bookmark, bookmark_list, category_based_list,
                    category_list, deactivate_blog, post_details,
                    subscribe_category, tag_based_list, writters_posts)

app_name = "post"

urlpatterns = [
    path('', PostList, name='post_list'),
    path('details/<slug:slug>', post_details, name='post_details'),
    path('write/', CreatePost.as_view(), name='create_post'),
    path('edit/<pk>/', UpdatePost.as_view(), name='edit_blog'),
    path('my-blogs/', MyPosts, name='my_blogs'),
    path('deactivate-blog/<pk>/', deactivate_blog, name="deactivate_blog"),
    path('blog-delete/<int:pk>/', BlogDelete.as_view(), name="blog_delete"),

    path('add-bookmark/', bookmark, name="bookmark"),
    path('bookmark-list/', bookmark_list, name="bookmark_list"),


    path('category/<slug:category_slug>/',
         category_based_list, name='category_based_list'),
    path('tag/<slug:slug>/', tag_based_list, name="tag_based_list"),

    path("writter-posts/<slug:slug>/", writters_posts, name="writters_posts"),
    path('subscribe-category/', subscribe_category, name="subscribe_category"),
    path('category-list/', category_list, name="category_list"),
]

scientific_application/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
    path('like/', include('like.urls', namespace="like")),
    path('comment/', include('comment.urls', namespace="comment")),
    path('keep/', include('keep.urls', namespace="keep")),
    path('notification/', include('notification.urls', namespace="notification")),
    path("", include("post.urls", namespace="post")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/views.py
import json

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.core.paginator import Paginator
from django.http.response import (HttpResponse, HttpResponseRedirect,
                                  JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views.generic import CreateView, ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import DeleteView, UpdateView
from taggit.models import Tag

from account.models import Follow
from comment.forms import CommentForm
from comment.models import Comment
from like.models import Like
from notification.models import Notification

from .models import Bookmark, Category, CategorySubscribe, Post
from .permissions import (LoginAndAuthorRequiredMixin,
                          LoginRequiredAndIsAuthorAndIsRightUserMixin,
                          login_and_is__author_required)

# Create your views here.
User = get_user_model()

# class PostList(ListView):
#     context_object_name = 'posts'
#     ordering = ("-id", )
#     paginate_by = 7
#     model = Post
#     template_name = 'post/post_list.html'

#     def get_context_data(self, **kwargs):
#         context = super(PostList, self).get_context_data(**kwargs)
#         context.update({
#             'categories': Category.objects.all(),
#         })
#         return context


def PostList(request):
    if request.user.is_authenticated:
        subscribed_categories = CategorySubscribe.objects.filter(
            subscriber=request.user)
        my_category_ids = []

        for i in subscribed_categories:
            my_category_ids.append(i.subscribed_category.id)

        following_list = Follow.objects.filter(follower=request.user)

        following_posts = Post.objects.filter(
            user__in=following_list.values_list('following'))
        subscribed_posts = Post.objects.filter(
            is_active=True).filter(category_id__in=my_category_ids)

        posts = following_posts.union(subscribed_posts).order_by("-id")

        # posts = Post.objects.filter(is_active=True).filter(category_id__in=my_category_ids).order_by("-id")
        latest_post = posts.first()
        paginator = Paginator(posts, 7)
        page_number = request.GET.get('page')
        posts = paginator.get_page(page_number)

        top_6_read_post = Post.objects.filter(
            is_active=True).order_by("-click_count")[:6]

        # most_read_post = Post.objects.filter()
        all_categories = Category.objects.all()

        context = {
            'posts': posts,
            'all_categories': all_categories,
            'top_6_read_post': top_6_read_post,
            'latest_post': latest_post,
            'subscribed_categories': subscribed_categories,
        }
        return render(request, 'post/post_list.html', context)
    else:
        posts = Post.objects.filter(is_active=True).order_by("-id")
        latest_post = posts.first()
        paginator = Paginator(posts, 7)
        page_number = request.GET.get('page')
        posts = paginator.get_page(page_number)

        top_6_read_post = Post.objects.filter(
            is_active=True).order_by("-click_count")[:6]

        # most_read_post = Post.objects.filter()
        all_categories = Category.objects.all()

        context = {
            'posts': posts,
            'all_categories': all_categories,
            'top_6_read_post': top_6_read_post,
            'latest_post': latest_post,
        }
        return render(request, 'post/post_list.html', context)


@login_required
def subscribe_category(request):
    if request.method == "POST":
        user = request.user
        pk = request.POST.get('pk', None)
        subscribed_category = get_object_or_404(Category, pk=pk)

        already_subscribed = CategorySubscribe.objects.filter(
            subscriber=user, subscribed_category=subscribed_category)
        if not already_subscribed:
            subscribe = CategorySubscribe(
                subscriber=user, subscribed_category=subscribed_category)
            subscribe.save()
            message = 'subscribed'
        else:
            already_subscribed.delete()
            message = 'unsubscribed'
    context = {
        "message": message,
    }
    return HttpResponse(json.dumps(context), content_type='application/json')


@login_required
def category_list(request):
    all_category = Category.objects.all()

    my_subscribed_category = CategorySubscribe.objects.filter(
        subscriber=request.user)
    my_subscribed_category_ids = []

    for i in my_subscribed_category:
        my_subscribed_category_ids.append(i.subscribed_category.id)

    context = {
        "my_subscribed_category_ids": my_subscribed_category_ids,
        "all_category": all_category,
    }
    return render(request, 'post/category_list.html', context)


# @login_required
# def category_list(request):
#     all_categories = Category.objects.all()

#     #subscribed category
#     subscribed_categories = CategorySubscribe.objects.filter(subscriber=request.user)
#     subscribed_category_list = []
#     for i in subscribed_categories:
#         abc= Category.objects.filter(name=i.subscribed_category.name)
#         subscribed_category_list.append(abc)
#     print(subscribed_category_list)


#     not_subscribed_category_list = []
#     for i in all_categories:
#         print(i)
#         if i in subscribed_category_list:
#             pass
#         else:
#             not_subscribed_category_list.append(i)
#     # not_subscribed_categories = Category.objects.exclude(id__in=subscribed_category_list)

#     print(not_subscribed_category_list)

#     # print(not_subscribed_categories)

    # context = {
    #     'subscribed_categories':subscribed_categories,
    #     # 'categories': categories,
    # }
    # return render(request, 'post/category_list.html', context)

# def category_toggle(request,pk):


class CreatePost(LoginAndAuthorRequiredMixin, CreateView):
    model = Post
    template_name = 'post/create_post.html'
    fields = ('post_title', 'category', 'tags', 'post_content', 'thumbnail',)
    success_url = "post:my_blogs"

    def form_valid(self, form):
        post_object = form.save(commit=False)
        post_object.user = self.request.user

        post_object.save()
        form.save_m2m()
        return HttpResponseRedirect(reverse('post:my_blogs'))


def post_details(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if post.is_active:
        post.click_count += 1
        post.save()

        comment_list = Comment.objects.filter(target_post=post).order_by("-id")
        total_comments = comment_list.count()
        paginator = Paginator(comment_list, 5)
        page_number = request.GET.get('page')

        comments_pagination = []
        if not page_number == None:
            for i in range(1, int(page_number)+1):
                comments_pagination.append(paginator.get_page(i))

        comment_list = paginator.get_page(page_number)
        if comment_list:
            last_pagination_comment_id = comment_list[0].id
        

        comments = []
        for i in comments_pagination:
            for j in i:
                comments.append(j)

        recommended_posts = Post.objects.filter(
            category=post.category).filter(is_active=True).order_by("-id")[:6]

        if request.user.is_authenticated:
            comment_form = CommentForm()
            already_liked = Like.objects.filter(
                liked_post=post, liker_post=request.user)
            already_bookmarked = Bookmark.objects.filter(
                bookmarked_post=post, user=request.user)

            if already_bookmarked:
                bookmarked = True
            else:
                bookmarked = False

            if already_liked:
                liked = True
            else:
                liked = False

            if request.method == 'POST':
                comment_form = CommentForm(request.POST)
                if comment_form.is_valid():
                    comment = comment_form.save(commit=False)
                    comment.user = request.user
                    comment.target_post = post
                    comment.save()
                    
                    if not comment.user == post.user:
                        sender = comment.user
                        user = post.user
                        post = post
                        comment = comment
                        notification_type = 2
                        notify = Notification(
                            sender=sender, post=post,comment=comment, user=user, notification_type=notification_type)
                        notify.save()
                    
                    
                    return HttpResponseRedirect(f'/details/{slug}#comment-part')
                    # return HttpResponseRedirect(reverse('post:post_details', kwargs={'slug': slug}))
            
            if comment_list:
                context = {'post': post, 'liked': liked, 'comment_form': comment_form, "total_comments": total_comments, "last_pagination_comment_id": last_pagination_comment_id,
                       "comment_list": comment_list, "comments": comments, 'bookmarked': bookmarked, "recommended_posts": recommended_posts}
            else:
                context = {'post': post, 'liked': liked, 'comment_form': comment_form, "total_comments": total_comments,
                       "comment_list": comment_list, "comments": comments, 'bookmarked': bookmarked, "recommended_posts": recommended_posts}
        else:
            if comment_list:

templates/post/category_list.html
{% extends 'base.html' %}
{% block title %}Category List{% endblock title %}
{% block content %}
    <div class="container">
        <h2>Subscribe Category to show right article</h2>
        <hr class="dropdown-divider">
        <div class="my-2">
            {% for category in all_category %}
                <a href="{% url 'post:category_based_list' category.slug %}" class="btn {% if category.id in my_subscribed_category_ids %} btn-success {% else %} btn-outline-success {% endif %} btn-sm m-1">{{ category.name }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/post/category_posts.html
{% extends 'base.html' %}
{% load humanize %}
{% block style %}
<style>
    .btn-sm-extra {
        border-radius: 1.2rem;
    }

    .text-small-c {
        font-size: 10px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .ha {
        width: 20px;
    }

    .gz {
        height: 20px;
    }

    .gx {
        border-radius: 4px;
    }

    .author-name {
        margin-left: 10px;
        color: #292929;
        font: 13px sohne;
        font-family: Helvetica, sans-serif;
    }
</style>
{% endblock style %}

{% block title %} {{ category.name }}{% endblock title %}
{% block content %}
    
        <hr class="dropdown-divider">
            
        <div class="container">
            <div class="container col-xxl-8 px-4 py-3">
                <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                    <div class="col-10 col-sm-8 col-lg-6">
                        <img src="{{ category.image.url }}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                    </div>
                    <div class="col-lg-6">
                        <h1 class="display-5 fw-bold lh-1 mb-3">{{ category.name }}</h1>
                        <p class="lead">
                            Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.
                        </p>
                        {% if request.user.is_authenticated %}
                            <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                                <button type="button" class="btn {% if already_subscribed %} btn-success {% else %} btn-danger {% endif %} px-4 me-md-2" id="subscribe" name="{{ category.pk }}">
                                    {% if already_subscribed %} UnSubscribe {% else %} Subscribe {% endif %}
                                </button>
                                <button type="button" class="btn btn-outline-secondary px-4">Default</button>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>

        <hr class="dropdown-divider">
        {% if posts %}
            {% for post in posts %}
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <a href="{% url 'post:post_details' post.slug %}">
                                <img src="{{ post.thumbnail.url }}" class="img-fluid rounded-start"
                                    alt="{{ post.post_title }}">
                            </a>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <div class="d-grid gap-2 d-md-flex justify-content-between">
                                    <p>
                                        <img src="{{ post.user.image.url }}" alt="" class="gx ha gz">
                                        <a href="{% url 'account:user_profile' post.user.account_slug %}" class="author-name"
                                            data-bs-toggle="popover"
                                            data-bs-trigger="hover focus"
                                            title="{{ post.user.name }}"
                                            data-bs-content="{{ post.user.headline }}"
                                        >
                                            {{ post.user.name }}
                                        </a>
                                    </p>
                                    
                                </div>
                                <a href="{% url 'post:post_details' post.slug %}" class="text-decoration-none text-black">
                                    <h5 class="card-title">{{ post.post_title }}</h5>
                                </a>
                                
                                <p class="card-text"><i class="bi bi-eye-fill"></i> {{ post.click_count }} &nbsp;&nbsp;&nbsp;&nbsp; <i class="bi bi-heart-fill"></i> {{post.liked_blog.count}} &nbsp;&nbsp;&nbsp;&nbsp; <i class="bi bi-chat-left-text-fill"></i> {{ post.post_comment.all|length }}</p>
                                <p class="card-text">
                                    <small class="text-muted">{{ post.created | naturaltime }}</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h2>Currently no post associated with this category</h2>
        {% endif %}

            {% if posts.paginator.num_pages > 1 %}
                <!-- Pagination-->
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if posts.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="">Previous</a>
                            </li>
                        {% endif %}
                        <span class="current">
                            <a class="page-link">
                                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                            </a>
                        </span>
                        {% if posts.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
    </div>
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
        </div>
    </footer>
{% endblock content %}

{% block script %}
    <script>
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })

    subscribe_unsubscribe_btn = document.getElementById("subscribe")

    $('#subscribe').click(function(){
        $.ajax({
            type: "POST",
            url: "{% url 'post:subscribe_category' %}",
            data: {
                'pk': $(this).attr('name'),
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: "json",
            success: function (response){
                if(response.message == "subscribed"){
                    subscribe_unsubscribe_btn.classList.remove("btn-danger")
                    subscribe_unsubscribe_btn.classList.add("btn-success")
                    subscribe_unsubscribe_btn.innerText = "Unsubscribe"
                }else if(response.message == "unsubscribed"){
                    subscribe_unsubscribe_btn.classList.remove("btn-success")
                    subscribe_unsubscribe_btn.classList.add("btn-danger")
                    subscribe_unsubscribe_btn.innerText = "Subscribe"
                }
            },
            error: function (rs, e){
                console.log("error");
            }
        });
    })

    </script>
{% endblock script %}

templates/post/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block style %}
    <style>
        .django-ckeditor-widget{
           width: 100%;
        }
        
    </style>
{% endblock style %}
{% block title %} Publish a Post {% endblock title %}
{% block content %}
    <div class="container">
        <form action="" method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <div class="d-grid gap-2 col-6 mx-auto my-3">
                <button type="submit" class="btn btn-primary btn-sm">Publish</button>
            </div>
        </form>
        <div class="flex-column justify-content-center mx-auto pb-3">
            <div class="text-center mt-3">
                <a href="{% url "account:user_profile" request.user.account_slug %}" class="btn btn-outline-secondary btn-sm">
                    Back to Profile
                </a>
            </div>
        </div>
    </div>
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
        </div>
    </footer>
{% endblock content %}

templates/post/my_posts.html
{% extends 'base.html' %}
{% load humanize %}
{% block style %}
<style>
    .btn-sm-extra {
        border-radius: 1.2rem;
    }

    .text-small-c {
        font-size: 10px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .ha {
        width: 20px;
    }

    .gz {
        height: 20px;
    }

    .gx {
        border-radius: 4px;
    }

    .author-name {
        margin-left: 10px;
        color: #292929;
        font: 13px sohne;
        font-family: Helvetica, sans-serif;
    }
</style>
{% endblock style %}
{% block title %} {{ request.user.name }}{% endblock title %}
{% block content %}
    <hr class="dropdown-divider">
    <hr class="dropdown-divider">
    <div class="container">
        <center><h2>My Articles</h2></center>
        {% for post in posts %}
            <div class="card mb-3" style="max-width: 100%;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <a href="{% url 'post:post_details' post.slug %}">
                            <img src="{{ post.thumbnail.url }}" class="img-fluid rounded-start"
                                alt="{{ post.post_title }}">
                        </a>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <div class="d-grid gap-2 d-md-flex justify-content-between">
                                <p>
                                    <img src="{{ post.user.image.url }}" alt="" class="gx ha gz">
                                    <a href="{% url 'account:user_profile' post.user.account_slug %}" class="author-name"
                                        data-bs-toggle="popover"
                                        data-bs-trigger="hover focus"
                                        title="{{ post.user.name }}"
                                        data-bs-content="{{ post.user.headline }}"
                                    >
                                        {{ post.user.name }}
                                    </a>
                                </p>
                                
                                {% if post.is_active %}
                                    <span class="badge rounded-pill bg-success mb-3">active</span>
                                {% else %}
                                    <span class="badge rounded-pill bg-danger mb-3">deactive</span>
                                {% endif %}
                            </div>
                            <a href="{% url 'post:post_details' post.slug %}" class="text-decoration-none text-black">
                                <h5 class="card-title">{{ post.post_title }}</h5>
                            </a>
                            
                            <p class="card-text"><i class="bi bi-eye-fill"></i> {{ post.click_count }} &nbsp;&nbsp;&nbsp;&nbsp; <i class="bi bi-heart-fill"></i> {{post.liked_blog.count}} &nbsp;&nbsp;&nbsp;&nbsp; <i class="bi bi-chat-left-text-fill"></i> {{ post.post_comment.all|length }}</p>
                            <p class="card-text">
                                <small class="text-muted">{{ post.created | naturaltime }}</small>
                                {% if post.is_active %}
                                    <a href="{% url 'post:deactivate_blog' post.pk %}" class="btn btn-warning btn-sm">Deactivate</a>
                                {% else %}
                                    <a href="{% url 'post:deactivate_blog' post.pk %}" class="btn btn-success btn-sm">Activate</a>
                                    <a href="{% url 'post:blog_delete' post.pk %}" class="btn btn-danger btn-sm">Delete</a>
                                    <a href="{% url 'post:edit_blog' post.pk %}" class="btn btn-secondary btn-sm">Update</a>
                                {% endif %}
                            
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if posts.paginator.num_pages > 1 %}
            <!-- Pagination-->
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="">Previous</a>
                        </li>
                    {% endif %}
                    <span class="current">
                        <a class="page-link">
                            Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                        </a>
                    </span>
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
        
    </div>
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
        </div>
    </footer>
{% endblock content %}

{% block script %}
    <script>
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })

    </script>
{% endblock script %}